when@dev:
  nelmio_api_doc:
    areas: # to filter documented areas
      path_patterns:
        - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
      host_patterns: # document only routes with a host of the form api.*
        - ^api\.

    documentation:
      info:
        title: BookHelper API
        description: BookHelper API
        version: 1.0.0
      paths:
        /api/get_info:
          get:
            tags:
              - Info
            summary: 'Get info'
            description: 'Get info'
            responses:
              200:
                description: 'Successful operation'
              400:
                description: 'Invalid tag value'

        /api/get_books:
          post:
            tags:
              - Api
            summary: 'Get books'
            description: 'Get books'
            requestBody:
              required: true
              content:
                application/json:
                  schema:
                    type: array
                    items:
                      type: string
                    example: '{"author_id": 18, "genre_id": 11, "cost": {"min": 1, "max": 500}, "language_id": 49, "year": 2024, "age_rating": 6, "sort": "DESC", "number_of_page": {"min": 1, "max": 1000}}'

            responses:
              200:
                description: 'Successful operation'
              400:
                description: 'Invalid tag value'
