version: '3.9'

services:
  book-helper-mysql:
    image: mysql/mysql-server:8.0
    container_name: book-helper-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${BH_APP_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${BH_APP_MYSQL_DATABASE}
      MYSQL_USER: ${BH_APP_MYSQL_USER}
      MYSQL_PASSWORD: ${BH_APP_MYSQL_PASSWORD}
    ports:
      - "${BH_APP_MYSQL_PORT_EXTERNAL}:3306"
    volumes:
      - "${BH_APP_MYSQL_HOST_STORAGE_PATH}:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
    networks:
      - book-helper-network
    logging:
      driver: "json-file"
      options:
        max-size: "900m"
        max-file: "3"

volumes:
  book-helper-logs:

networks:
  book-helper-network:
    external: true
